spring.application.name=Job_portal_SystemAPI


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/final_java_service?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Hoangduc2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

logging.file.name=logs/application.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} - %-5level - %logger{50} - %msg%n
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.level.root=INFO
logging.level.job_portal_systemapi.repository=warn
logging.level.job_portal_systemapi.service=warn
logging.level.org.springframework=warn
logging.level.org.hibernate=warn
logging.level.org.hibernate.sql=warn
logging.console.enabled=true

#Config JWT
jwt-secret=chuoibimatdemahoachuoijwtdudaidetangbaomat
#Chu?i jwt ???c t?o ra s? t?n t?i trong 20'
jwt-expire=1200000
#refresh token s? t?n t?i trong 30 ngày
jwt-refresh-expire=2592000000

#l?y danh sach job mà ko l?y tr?ng thái closed

#cloudinary
#Cloudinary config
cloudinary-key-name=dgw3ijzxk
cloudinary-api-key=955846114985319
cloudinary-api-secret=taL1pZn_3ferLDZDi7lOEHBPT9s

#Cau hinh OTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ducgay233@gmail.com
spring.mail.password=hpjlsxxexzekktts

# Các thu?c tính b?o m?t ?i kèm c?a giao th?c SMTP
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.redis.host=localhost
spring.data.redis.port=6379